---
abstract: 'Read data from a NeuroSky MindWave headset'
author:
  - 'Tom Harrison <tomhrr@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Device-MindWave
no_index:
  directory:
    - t
    - inc
requires:
  Device::SerialPort: 0
  IO::Capture::Stderr: 0
  IO::File: 0
  List::Util: 0
  Scalar::Util: 0
  perl: 5.006
resources:
  repository: https://github.com/tomhrr/p5-Device-MindWave
version: 0.02
